/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.employeepayrollsql.controller;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Scanner;

import com.blz.employeepayrollsql.model.Contact;
import com.blz.employeepayrollsql.model.empPayrollDBService;

public class Emp_Payroll_JDBC_Main {
	public enum IOService {
		CONSOLE_IO, FILE_IO, DB_IO, REST_IO;
	}


	private static void listDrivers() {
		Enumeration<Driver> driverList = DriverManager.getDrivers();
		while (driverList.hasMoreElements()) {
			Driver driverClass = driverList.nextElement();
			System.out.println(" " + driverClass.getClass().getName());
		}
	}

	private List<Contact> employeePayrollList;
	
	public Emp_Payroll_JDBC_Main() {

	}

	// Constructor
	public Emp_Payroll_JDBC_Main(List<Contact> employeePayrollList) {
		this.employeePayrollList = employeePayrollList;
	}

	public static void main(String[] args) {
		ArrayList<Contact> employeePayrollList = new ArrayList<Contact>();
	}

	public List<Contact> readEmployeePayrollDatabase(IOService ioService) {
		if (ioService.equals(IOService.DB_IO)) {
			this.employeePayrollList=empPayrollDBService.readData();
		}
		
		return this.employeePayrollList;
	}

}
