/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeePayrollSQL;

import org.junit.Before;
import org.junit.Test;

import com.blz.employeepayrollsql.controller.Emp_Payroll_JDBC_Main;
import com.blz.employeepayrollsql.controller.Emp_Payroll_JDBC_Main.IOService;
import com.blz.employeepayrollsql.model.Contact;
import com.blz.employeepayrollsql.model.CustomPayrollException;

import junit.framework.Assert;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

@SuppressWarnings("deprecation")
public class Emp_Payroll_JDBC_Test {
	Emp_Payroll_JDBC_Main empPayrollService = null;

	@Before
	public void setup() {
		empPayrollService = new Emp_Payroll_JDBC_Main();
	}

	@Test
	public void givenEmployeePayrollServiceInDB_ShouldMatchEmployeeCount() {
		List<Contact> empPayrollData;
		try {
			empPayrollData = empPayrollService.readEmployeePayrollDatabase(IOService.DB_IO);
			Assert.assertEquals(5, empPayrollData.size());
		} catch (CustomPayrollException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenNewSalaryForEmployee_WhenUpdatedByPreapredStmt_ShouldSyncWithDB() {
		try {
			empPayrollService.readEmployeePayrollDatabase(IOService.DB_IO);
			empPayrollService.updateEmployeeSalaryInDBThenInList("Dev", 500000.00);
			boolean result = empPayrollService.checkEmployeePayrollListSyncWithDB("Dev");
			Assert.assertTrue(result);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
