/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeePayrollSQL;

import org.junit.Test;

import com.blz.employeepayrollsql.controller.Emp_Payroll_JDBC_Main;
import com.blz.employeepayrollsql.controller.Emp_Payroll_JDBC_Main.IOService;
import com.blz.employeepayrollsql.model.Contact;

import junit.framework.Assert;

import java.util.List;

@SuppressWarnings("deprecation")
public class Emp_Payroll_JDBC_Test {
	@Test
	public void givenEmployeePayrollServiceInDB_ShouldMatchEmployeeCount() {
		Emp_Payroll_JDBC_Main empPayrollService=new Emp_Payroll_JDBC_Main();
		List<Contact> empPayrollData=empPayrollService.readEmployeePayrollDatabase(IOService.DB_IO);
		Assert.assertEquals(3, empPayrollData.size());
		
	}
}
