/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeePayrollSQL;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Enumeration;

public class Emp_Payroll_JDBC_Main {
	public static void main(String[] args) {
		String jdbcURL = "jdbc:mysql://localhost:3306/payroll_service";
		String userName = "root";
		String password = "Kumar@12345";
		Connection con;

		// 1 . Load driver class -> MYSQL JDBC
		try {
			Class.forName("com.mysql.jdbc.Driver");
			System.out.println("Driver Loaded");

		} catch (ClassNotFoundException e) {
			throw new IllegalStateException("Can not find the driver in class path ! " + e);
		}

		// List All Available Drivers
		listDrivers();

		// 2. create Connection object
		try {
			con = DriverManager.getConnection(jdbcURL, userName, password);
			System.out.println("Connection Done..!!!" + con);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private static void listDrivers() {
		Enumeration<Driver> driverList = DriverManager.getDrivers();
		while (driverList.hasMoreElements()) {
			Driver driverClass = driverList.nextElement();
			System.out.println(" " + driverClass.getClass().getName());
		}
	}
}
